apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: loadaiax3459-tenant-component
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: loadaiax3459-tenant-component
    app.kubernetes.io/part-of: loadaiax3459-tenant-app
  name: loadaiax3459-tenant-component
  namespace: loadaiax3459-tenant
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: loadaiax3459-tenant-component
    weight: null
status: {}
